language: objective-c
osx_image: xcode8
branches:
  only:
  - master
env:
  global:
  - SDK="iphonesimulator"
  matrix:
    - DESTINATION="OS=10.0,name=iPhone 6s" CONFIGURATION="Debug" SCHEME="Tests"
    - DESTINATION="OS=10.0,name=iPhone 6s" CONFIGURATION="Release" SCHEME="Overlay"
    - DESTINATION="OS=10.0,name=iPad Pro (9.7 inch)" CONFIGURATION="Debug" SCHEME="Tests"
    - DESTINATION="OS=10.0,name=iPad Pro (9.7 inch)" CONFIGURATION="Release" SCHEME="Overlay"
script:
  - set -o pipefail
  - xcodebuild test -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration "$CONFIGURATION" | xcpretty
