language: objective-c
osx_image: xcode8
branches:
  only:
    - master
env:
  global:
    - SDK="iphonesimulator"
  matrix:
    - DESTINATION="OS=9.0,name=iPhone 6s" MODE="test" CONFIGURATION="Debug" SCHEME="Tests"
    - DESTINATION="OS=9.0,name=iPhone 6s Plus" MODE="build" CONFIGURATION="Release" SCHEME="Overlay"
    - DESTINATION="OS=9.0,name=iPad Air" MODE="test" CONFIGURATION="Debug" SCHEME="Tests"
    - DESTINATION="OS=9.0,name=iPad Air 2" MODE="build" CONFIGURATION="Release" SCHEME="Overlay"
    - DESTINATION="OS=10.0,name=iPhone 7" MODE="test" CONFIGURATION="Debug" SCHEME="Tests"
    - DESTINATION="OS=10.0,name=iPhone 7 Plus" MODE="build" CONFIGURATION="Release" SCHEME="Overlay"
    - DESTINATION="OS=10.0,name=iPad Pro (9.7 inch)" MODE="test" CONFIGURATION="Debug" SCHEME="Tests"
    - DESTINATION="OS=10.0,name=iPad Pro (12.9 inch)" MODE="build" CONFIGURATION="Release" SCHEME="Overlay"
script:
  - set -o pipefail
  - xcodebuild "$MODE" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration "$CONFIGURATION" | xcpretty
