language: objective-c
osx_image: xcode8
branches:
  only:
  - master
env:
  global:
  - SCHEME="Overlay"
  - SDK="iphonesimulator"
  matrix:
    - DESTINATION="OS=10.0,name=iPhone 6s" CONFIGURATION="Debug"
    - DESTINATION="OS=10.0,name=iPhone 6s" CONFIGURATION="Release"
    - DESTINATION="OS=10.0,name=iPad Pro (9.7 inch)" CONFIGURATION="Debug"
    - DESTINATION="OS=10.0,name=iPad Pro (9.7 inch)" CONFIGURATION="Release"
script:
  - set -o pipefail
  - xcodebuild test -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration "$CONFIGURATION" ENABLE_TESTABILITY=YES | xcpretty
